### PR TITLE
fine adjustments to node positions, addition of lost and found node

### PR DESCRIPTION
**Pull request by AlexSkylark**
Hello, Alex Starlight here :), I'm the author of the HideEmptyFilters mod (https://github.com/AlexSkylark/HideEmptyFilters)

I'll send you a msg on the forums too, but I'll repeat it here. I very VERY much loved your mod, so I decided to tinker with it a bit to find what could be a more aesthetically-pleasing solution to the "what to do with unsupported parts" issue. I just followed an approach similar to what RP-1 does, putting all parts with no explicit support of this mod into a "lost and found" node, which will sit just above the start node and with a 1sp cost. (this solution also had the help of the wonderful @JadeOfMaar of the Wild Blue Industries mods, BTW :D)

I also took the liberty of nudging around a few of the starting nodes to make the tree look a bit more symmetrical in game. Anyhow, you can see how my changes made it look here: 
image

Anyhow, I hope you like those proposed changes. This is an incredible mod that will probably get very popular very soon, and I'm very happy to offer this small contribution. Stay well, fellow modder :D

### CODE REVIEW

**Comment by hersfeldtn** [comment]
Looks like a good idea, though the one thing I didn't like was it was picking up things like the comet parts so I fiddled around and added an extra node for intentionally excluded parts that then gets deleted by this patch (and I had to move the lost and found node a bit because techtree edit insists on forcing arrows to come out of the left or right side of nodes.

**Comment by AlexSkylark** [comment]
Hey, thanks for the merge! I'm glad to have contributed :) and you're right, there's also the consideration of parts not meant to be researched (like from contract packs, for example).

Anyhow, for reference, you can manipulate which side the arrows leave from and come to each node of the tree if you hand-edit the cfg file (you can do it on GPTT_yonge.cfg after saving it in the tech tree editor) and mess around with the LineFrom and LineTo of the "Parent" subnodes (example on lines 21 and 22 of the file. Valid values for both are LEFT, RIGHT, BOTTOM and TOP)

**Comment by hersfeldtn** [comment]
Yeah I know but if I'm mostly going to be doing edits by techtree-edit I'd have to fix that every time I update.

**Comment by AlexSkylark** [comment]
This is fair. At any rate, the place where it ultimately sat is not bad at all :)

**Pull request merged**
